# _tests/test_config.yaml
# 統合テスト用最小設定

model:
  encoder:
    type: "tcn"
    input_dim: 3          # テスト用小次元
    output_dim: 1         # スカラー特徴量（固定）
    channels: 16          # 軽量化
    layers: 3             # 軽量化
    kernel_size: 3
    activation: "GELU"
    dropout: 0.0
    center_output: true

  decoder:
    type: "tcn"
    output_dim: 3         # テスト用小次元
    window: 4             # 軽量化
    tau: 1
    hidden: 16            # 軽量化
    ma_kernel: 8          # 軽量化
    gru_hidden: 16        # 軽量化
    activation: "GELU"
    dropout: 0.0

ssm:
  realization:
    past_horizon: 5       # テスト用短縮
    jitter: 1e-3
    cond_thresh: 1e12
    rank: 3               # 軽量化
    reg_type: "sum"

  df_state:
    feature_dim: 8        # 軽量化
    lambda_A: 1e-2        # 安定性のため大きめ
    lambda_B: 1e-2        # 安定性のため大きめ
    feature_net_config:
      hidden_sizes: [16, 16]  # 軽量化
      activation: "ReLU"
      dropout: 0.0
    cross_fitting_config:
      n_blocks: 3         # 軽量化
      min_block_size: 5

  df_observation:
    obs_feature_dim: 6    # 軽量化
    lambda_B: 1e-2        # 安定性のため大きめ
    lambda_dB: 1e-2       # 安定性のため大きめ
    obs_net_config:
      hidden_sizes: [12, 12]  # 軽量化
      activation: "ReLU"
      dropout: 0.0
    cross_fitting_config:
      n_blocks: 3         # 軽量化
      min_block_size: 5

training:
  # Phase-1設定（テスト用短縮）
  phase1_epochs: 3        # 短縮
  T1_iterations: 2        # 短縮
  T2_iterations: 1        # 短縮
  df_a_warmup_epochs: 1   # 短縮
  
  # Phase-2設定（テスト用短縮）
  phase2_epochs: 2        # 短縮
  lambda_cca: 0.01
  update_strategy: "all"
  
  # 学習率（テスト用）
  lr_phi: 1e-3
  lr_psi: 1e-3
  lr_encoder: 5e-4
  lr_decoder: 5e-4
  
  # ログ設定
  log_interval: 1
  save_interval: 100      # 保存無効化
  verbose: true

# テスト用実験設定
experiment:
  name: "integration_test"
  description: "統合テスト用最小設定"
  seed: 42

# デバッグ設定
debug:
  save_intermediate: false
  profile_training: false
  continue_on_error: false