# configs/evaluation_config.yaml
# タスク4: フィルタリング状態推定・評価 専用設定

# 評価実験基本設定
evaluation:
  experiment_name: "filtering_performance_evaluation"
  output_base_dir: "results/task4_evaluation"
  save_detailed_results: true
  create_visualizations: true
  
  # 評価対象データ設定
  data:
    test_split: "test"           # 'test', 'val', 'all'のいずれか
    calibration_ratio: 0.25      # キャリブレーション用データ比率
    max_evaluation_length: null   # null=全データ、数値=サンプル数制限
    
  # 評価指標設定
  metrics:
    # 精度指標
    accuracy:
      - "mse"              # 平均二乗誤差
      - "mae"              # 平均絶対誤差  
      - "rmse"             # 二乗平均平方根誤差
      - "correlation"      # 相関係数
      - "relative_error"   # 相対誤差
    
    # 不確実性指標
    uncertainty:
      - "coverage_68"      # 68%信頼区間カバレッジ
      - "coverage_95"      # 95%信頼区間カバレッジ
      - "coverage_99"      # 99%信頼区間カバレッジ
      - "interval_width"   # 区間幅
      - "calibration_error" # キャリブレーション誤差
    
    # 計算効率指標
    efficiency:
      - "processing_time"  # 処理時間
      - "memory_usage"     # メモリ使用量
      - "throughput"       # スループット
    
    # 尤度指標
    likelihood:
      - "log_likelihood"   # 対数尤度
      - "perplexity"      # パープレキシティ
      
  # 比較実験設定
  comparison:
    methods:
      - "batch_filtering"    # バッチフィルタリング
      - "online_filtering"   # オンラインフィルタリング
      - "deterministic_vs_kalman"  # 決定的 vs Kalman比較
    
    statistical_tests:
      enabled: true
      significance_level: 0.05
      
# フィルタリング実行設定
filtering:
  # バッチフィルタリング
  batch:
    return_likelihood: true
    chunk_size: null          # null=一括処理、数値=チャンク分割
    
  # オンラインフィルタリング  
  online:
    progress_interval: 100    # 進捗表示間隔
    state_reset: true         # 各実験前に状態リセット
    timing_precision: "high"  # "high", "standard"
    
# 不確実性分析設定
uncertainty_analysis:
  enabled: true
  
  # 信頼区間設定
  confidence_intervals:
    levels: [0.68, 0.90, 0.95, 0.99]  # 信頼水準
    
  # キャリブレーション設定
  calibration:
    n_bins: 10               # ビン数
    methods: ["ece", "reliability_diagram"]
    
  # 時系列分析
  temporal_analysis:
    trend_analysis: true      # 傾向分析
    volatility_analysis: true # 変動分析
    autocorr_analysis: true   # 自己相関分析

# 可視化設定
visualization:
  enabled: true
  format: "png"              # "png", "pdf", "svg"
  dpi: 300
  style: "seaborn-v0_8"     # Matplotlibスタイル
  
  # 作成する図表
  plots:
    - "uncertainty_distribution"    # 不確実性分布
    - "temporal_uncertainty"        # 時系列不確実性
    - "error_vs_uncertainty"        # 誤差-不確実性散布図
    - "confidence_intervals"        # 信頼区間サンプル
    - "calibration_curve"           # キャリブレーション曲線
    - "coverage_rates"              # カバレッジ率
    - "method_comparison"           # 手法比較
    
  # 図のサイズ設定
  figure_size:
    single_plot: [8, 6]
    multi_plot: [12, 8]
    comparison_plot: [10, 6]

# 結果出力設定
output:
  # 保存形式
  formats:
    detailed: "json"         # 詳細結果 ("json", "pickle")
    summary: "csv"           # サマリ ("csv", "xlsx")  
    numerical: "npz"         # 数値データ ("npz", "hdf5")
    
  # ファイル命名
  naming:
    include_timestamp: true
    include_config_hash: false
    custom_suffix: null
    
  # 圧縮設定
  compression:
    enabled: false
    format: "zip"            # "zip", "tar.gz"

# 実験再現性設定  
reproducibility:
  # 乱数シード管理
  random_seeds:
    torch_seed: 42
    numpy_seed: 42
    python_seed: 42
    
  # 環境情報記録
  record_environment:
    system_info: true        # OS、CPU、メモリ情報
    library_versions: true   # ライブラリバージョン
    git_info: false          # Git情報（利用可能な場合）
    
  # 設定保存
  save_config: true
  config_format: "yaml"     # "yaml", "json"

# デバイス・計算設定
computation:
  device: "auto"             # "auto", "cpu", "cuda"
  dtype: "float32"           # "float32", "float64"
  
  # 数値安定性
  numerical_stability:
    enable_amp: false        # Automatic Mixed Precision
    gradient_clipping: false
    
  # メモリ管理
  memory:
    clear_cache: true        # 実験間でキャッシュクリア
    monitor_usage: true      # メモリ使用量監視

# ログ設定
logging:
  level: "INFO"              # "DEBUG", "INFO", "WARNING", "ERROR"
  console_output: true
  file_output: true
  
  # ログ内容
  log_content:
    experiment_progress: true
    performance_metrics: true
    error_details: true
    timing_information: true
    memory_usage: true

# デバッグ・テスト設定
debug:
  enabled: false
  
  # クイック実行（デバッグ用）
  quick_mode:
    enabled: false
    max_samples: 100         # 処理サンプル数制限
    skip_visualization: true
    reduce_metrics: true
    
  # 詳細出力
  verbose_output:
    intermediate_results: false
    tensor_shapes: false
    timing_breakdown: false

# 並列処理設定（将来拡張用）
parallelization:
  enabled: false
  n_jobs: 1
  backend: "threading"      # "threading", "multiprocessing"

---
# クイックテスト用設定
quick_test_evaluation:
  # 最小限の評価設定（開発・デバッグ用）
  evaluation:
    experiment_name: "quick_filtering_test"
    output_base_dir: "results/quick_test"
    save_detailed_results: false
    create_visualizations: false
    
  data:
    test_split: "test"
    calibration_ratio: 0.2
    max_evaluation_length: 100  # 100サンプルのみ
    
  metrics:
    accuracy: ["mse", "mae"]
    uncertainty: ["coverage_95"]
    efficiency: ["processing_time"]
    
  filtering:
    batch:
      return_likelihood: false
    online:
      progress_interval: 50
      
  uncertainty_analysis:
    enabled: false
    
  visualization:
    enabled: false
    
  debug:
    enabled: true
    quick_mode:
      enabled: true
      max_samples: 100
      skip_visualization: true

---
# 詳細評価用設定
comprehensive_evaluation:
  # 包括的評価設定（論文用・詳細分析）
  evaluation:
    experiment_name: "comprehensive_filtering_evaluation"
    output_base_dir: "results/comprehensive_evaluation"
    save_detailed_results: true
    create_visualizations: true
    
  data:
    test_split: "test"
    calibration_ratio: 0.3
    max_evaluation_length: null  # 全データ
    
  metrics:
    accuracy: ["mse", "mae", "rmse", "correlation", "relative_error"]
    uncertainty: ["coverage_68", "coverage_95", "coverage_99", "interval_width", "calibration_error"]
    efficiency: ["processing_time", "memory_usage", "throughput"]
    likelihood: ["log_likelihood", "perplexity"]
    
  comparison:
    methods: ["batch_filtering", "online_filtering", "deterministic_vs_kalman"]
    statistical_tests:
      enabled: true
      significance_level: 0.05
      
  filtering:
    batch:
      return_likelihood: true
    online:
      progress_interval: 200
      timing_precision: "high"
      
  uncertainty_analysis:
    enabled: true
    confidence_intervals:
      levels: [0.68, 0.90, 0.95, 0.99]
    calibration:
      n_bins: 15
      methods: ["ece", "reliability_diagram"]
    temporal_analysis:
      trend_analysis: true
      volatility_analysis: true
      autocorr_analysis: true
      
  visualization:
    enabled: true
    dpi: 300
    plots: 
      - "uncertainty_distribution"
      - "temporal_uncertainty"
      - "error_vs_uncertainty"
      - "confidence_intervals"
      - "calibration_curve"
      - "coverage_rates"
      - "method_comparison"
      
  output:
    formats:
      detailed: "json"
      summary: "csv"
      numerical: "npz"
    compression:
      enabled: true
      format: "zip"
      
  reproducibility:
    record_environment:
      system_info: true
      library_versions: true
      git_info: true
    save_config: true
    
  logging:
    level: "INFO"
    console_output: true
    file_output: true
    log_content:
      experiment_progress: true
      performance_metrics: true
      timing_information: true
      memory_usage: true

# ==========================================
# 推論設定（InferenceModel用）
# ==========================================
inference:
  # フィルタリング設定
  filtering:
    # ノイズ推定設定
    noise_estimation:
      method: "residual_based"  # 式45-46
      gamma_Q: 1.0e-6          # Q行列正則化
      gamma_R: 1.0e-6          # R行列正則化
      use_calibration: true    # キャリブレーションデータ使用

    # 初期化設定
    initialization:
      method: "data_driven"    # 初期状態推定法 ("data_driven" | "zero")
      n_init_samples: 50       # 初期化用サンプル数

  # ストリーミング設定
  streaming:
    buffer_size: 100           # 内部バッファサイズ
    batch_processing: false    # バッチ処理フラグ
    anomaly_detection: true    # 異常検知有効化
    anomaly_threshold: 3.0     # 異常検知閾値（標準偏数倍数）

  # 数値安定性設定
  numerical:
    condition_threshold: 1.0e12  # 条件数閾値
    min_eigenvalue: 1.0e-8       # 最小固有値
    jitter: 1.0e-6               # ジッター項

  # 出力設定
  output:
    save_states: true          # 状態系列保存
    save_covariances: false    # 共分散保存（メモリ節約）
    save_likelihoods: true     # 尤度保存

# ==========================================
# モデル設定（test_stable_config.yamlから）
# ==========================================
model:
  encoder:
    input_dim: 6
    channels: 32
    layers: 4
    kernel_size: 3
    activation: "GELU"
    dropout: 0.1

  decoder:
    output_dim: 6
    window: 8
    tau: 1
    hidden: 32
    ma_kernel: 16
    gru_hidden: 16
    activation: "GELU"
    dropout: 0.1

# ==========================================
# SSM設定（test_stable_config.yamlから）
# ==========================================
ssm:
  realization:
    past_horizon: 10
    jitter: 1e-6
    cond_thresh: 1e10
    rank: 4
    reg_type: "sum"

  df_state:
    feature_dim: 24
    lambda_A: 1e-3
    lambda_B: 1e-3
    
    feature_net:
      hidden_sizes: [48, 48]
      activation: "ReLU"
      dropout: 0.1
      
    cross_fitting:
      n_blocks: 4
      min_block_size: 15

  df_observation:
    obs_feature_dim: 12
    lambda_B: 1e-3
    lambda_dB: 1e-3
    
    obs_net:
      hidden_sizes: [24, 24]
      activation: "ReLU"
      dropout: 0.1
      
    cross_fitting:
      n_blocks: 4
      min_block_size: 15

# ==========================================
# 学習設定（test_stable_config.yamlから）
# ==========================================
training:
  use_kalman_filtering: true
  
  phase1:
    epochs: 10
    T1_iterations: 5
    T2_iterations: 3
    
    df_a:
      warmup_epochs: 3
      lr: 5e-3
      
    df_b:
      start_epoch: 3
      lr: 5e-3

  phase2:
    epochs: 20
    lr_encoder: 5e-4
    lr_decoder: 5e-4
    lr_phi: 5e-4
    lr_psi: 5e-4
    lambda_cca: 0.1
    update_strategy: "all"

  device: "auto"
  seed: 42
  gradient_clip: 1.0
  
  early_stopping:
    patience: 5
    min_delta: 1e-5
    
  checkpoint:
    save_every: 5
    keep_best: true

  # Kalmanフィルタリング設定
  kalman_filtering:
    enabled: true