# データファイル（用途別に分割した .npz を指定）
data:
  train_file: 'ETTm1_train.npz'
  val_file:   'ETTm1_val.npz'
  pred_file:  'ETTm1_test.npz'

# モデル定義：動的に切り替え可能
model:
  # encoder_class: 'models.encoder._mlpEncoder'    # 文字列でクラス名を指定
  encoder:
    type: "_mlp"
    input_dim:  7
    output_dim: 8
    hidden_sizes: !!seq [!!int 64, !!int 64, !!int 64]
    activation: "Tanh"

  # decoder_class: 'models.decoder._mlpDecoder'
  decoder:
    type: "_mlp"
    input_dim:  8
    output_dim: 7
    hidden_sizes: !!seq [!!int 64, !!int 64, !!int 64]
    activation: "Tanh"

# SSM（状態空間モデル）構成
ssm:
  realization:
    past_horizon: 20
    jitter: !!float 1e-3
    cond_thresh: !!float 1e12
    rank: 20
    reg_type: "sum"

  observation:
    past_horizon: 20
    kernel: 'rbf'
    gamma:  !!float 0.1
    reg_lambda: !!float 1e-4

# 訓練ハイパーパラメータ
train:
  batch_size: 1
  seq_len: 500
  stride: 100
  shuffle: False
  lr: !!float 1e-3
  epochs: 20
  max_step: 50
  sv_weight:  !!float 0

# 検証時バッチサイズ
eval:
  batch_size: 1
  seq_len: 2000
  stride: 100

# 予測時バッチサイズ
pred:
  batch_size: 1
  warmup: 300
  forecast_steps: 96