# configs/filtering_evaluation_config.yaml
# run_filtering_evaluation.py用のシンプル設定

# 標準設定（mode='standard'時に使用）
evaluation:
  experiment_name: "filtering_evaluation_test"
  save_detailed_results: true
  create_visualizations: true
  data:
    test_split: "test"
    calibration_ratio: 0.2
    max_evaluation_length: null

  metrics:
    accuracy:
      - "mse"
      - "mae"
      - "rmse"
    uncertainty:
      - "coverage_95"
    efficiency:
      - "processing_time"

filtering:
  batch:
    return_likelihood: true
    chunk_size: null

uncertainty_analysis:
  enabled: true
  confidence_intervals:
    levels: [0.95]

visualization:
  enabled: true
  format: "png"
  plots:
    - "confidence_intervals"
    - "method_comparison"

output:
  formats:
    detailed: "json"
    summary: "csv"

computation:
  device: "auto"
  dtype: "float32"

logging:
  level: "INFO"
  console_output: true

# 推論設定
inference:
  noise_estimation_method: "residual_based"
  gamma_Q: 1.0e-6
  gamma_R: 1.0e-6
  use_calibration: true
  initialization_method: "data_driven"
  n_init_samples: 20

# SSM設定（realization用）
ssm:
  realization:
    past_horizon: 2  # 短いテストデータ用
    jitter: 1e-6
    rank: 2

---
# クイックテスト設定（mode='quick'時に使用）
quick_test_evaluation:
  evaluation:
    experiment_name: "quick_filtering_test"
    save_detailed_results: false
    create_visualizations: false
    data:
      test_split: "test"
      calibration_ratio: 0.2
      max_evaluation_length: 50

    metrics:
      accuracy: ["mse"]
      uncertainty: ["coverage_95"]
      efficiency: ["processing_time"]

  filtering:
    batch:
      return_likelihood: false

  uncertainty_analysis:
    enabled: false

  visualization:
    enabled: false

  computation:
    device: "auto"

  logging:
    level: "INFO"

  # 推論設定
  inference:
    noise_estimation_method: "residual_based"
    gamma_Q: 1.0e-6
    gamma_R: 1.0e-6
    use_calibration: true
    initialization_method: "data_driven"
    n_init_samples: 20

  # SSM設定（realization用）
  ssm:
    realization:
      past_horizon: 2  # 短いテストデータ用
      jitter: 1e-6
      rank: 2