training:
  data_path: "data/sim_simple.npz"
  batch_size: 32
  epochs: 50
  lr: 1e-3

ssm:
  realization:
    past_horizon: 5
    jitter: 1e-6
    cond_thresh: 1e12
    rank: 3
  observation:
    kernel: "rbf"
    gamma: 1.0
    reg_lambda: 1e-3

visualization:
  output_dir: "results/figs"
