# configs/sl3000_config.yaml
# Stuart-Landau系 3000時点×6次元データ用本格実験設定
# sl3_T3000_dt0p01_seed42.npz 用最適化設定

# =====================================
# データ処理設定
# =====================================
data:
  train_ratio: 0.7    # 2100時点を学習用
  val_ratio: 0.2      # 600時点を検証用
  test_ratio: 0.1     # 300時点をテスト用
  normalization: "standard"
  handle_missing: "interpolate"
  batch_size: 64      # 長時系列用バッチサイズ
  num_workers: 8
  pin_memory: true

# =====================================
# モデル構成 - Stuart-Landau系最適化
# =====================================
model:
  encoder:
    input_dim: 6        # Stuart-Landau系6次元
    channels: 64        # 非線形動力学捕捉のため増加
    layers: 6           # 深層化で複雑な動力学学習
    kernel_size: 5      # 時間依存性捕捉のため拡大
    activation: "GELU"
    dropout: 0.15

  decoder:
    output_dim: 6       # 6次元出力
    window: 12          # 長時間依存性考慮
    tau: 1
    hidden: 64          # エンコーダと整合
    ma_kernel: 32       # 時間平滑化強化
    gru_hidden: 32      # 系列記憶能力向上
    activation: "GELU"
    dropout: 0.15

# =====================================
# 状態空間モデル（SSM）設定 - 連続動力学系対応
# =====================================
ssm:
  realization:
    past_horizon: 20    # Stuart-Landau系の長期記憶考慮
    jitter: 1e-6        # 数値安定性強化
    cond_thresh: 1e10   # 条件数制御厳格化
    rank: 4             # 次元削減で安定化
    reg_type: "sum"

  df_state:
    feature_dim: 48     # 豊富な特徴表現
    lambda_A: 1e-2      # 状態遷移正則化強化
    lambda_B: 1e-2      # 入力正則化強化

    feature_net:
      hidden_sizes: [96, 96, 64]  # 深層ネットワーク
      activation: "ReLU"
      dropout: 0.1

    cross_fitting:
      n_blocks: 6       # データ量に対応
      min_block_size: 20

  df_observation:
    obs_feature_dim: 24   # 観測特徴次元
    lambda_B: 1e-2        # 正則化強化
    lambda_dB: 1e-2       # 正則化強化

    obs_net:
      hidden_sizes: [48, 48, 32]  # 観測系列学習
      activation: "ReLU"
      dropout: 0.1

    cross_fitting:
      n_blocks: 6
      min_block_size: 20

# =====================================
# 学習設定 - Stuart-Landau系本格学習
# =====================================
training:
  use_kalman_filtering: true

  phase1:
    epochs: 30          # 学習時間短縮
    T1_iterations: 8    # Stage-1効率化
    T2_iterations: 6    # Stage-2効率化

    df_a:
      warmup_epochs: 5
      lr: 1e-3          # 学習率上げて高速化

    df_b:
      start_epoch: 5
      lr: 1e-3

  phase2:
    epochs: 40          # end-to-end学習短縮
    lr_encoder: 2e-4    # 学習率上げて高速化
    lr_decoder: 2e-4
    lr_phi: 2e-4
    lr_psi: 2e-4
    lambda_cca: 0.05    # CCA重み調整
    update_strategy: "all"

  device: "auto"
  seed: 42              # 再現性確保
  gradient_clip: 1.0

  early_stopping:
    patience: 8         # 早期終了で時間短縮
    min_delta: 1e-5     # 停止条件緩和

  checkpoint:
    save_every: 20
    keep_best: true

# =====================================
# Kalmanフィルタリング設定 - 連続系対応
# =====================================
kalman:
  noise_estimation:
    method: "mle"
    obs_noise_init: 1e-2  # Stuart-Landau系ノイズレベル
    state_noise_init: 5e-3
    min_noise: 1e-7
    max_noise: 1e0

  initialization:
    method: "data_driven"
    initial_cov_scale: 1.0

  numerical:
    jitter: 1e-7
    regularization: 5e-5
    condition_threshold: 1e12

# =====================================
# 評価設定 - 詳細分析
# =====================================
evaluation:
  metrics:
    - "mse"
    - "mae"
    - "rmse"
    - "correlation"
    - "spectral_density"   # 周波数解析
    - "phase_coherence"    # 位相一貫性

  forecasting:
    horizon: 20           # 中期予測評価
    n_samples: 200

  visualization:
    n_plot_samples: 500   # 詳細可視化
    plot_dimensions: 6    # 全次元プロット
    save_plots: true

  uncertainty_analysis:
    confidence_levels: [0.68, 0.95, 0.99]
    plot_uncertainty: true

# =====================================
# 実験管理設定
# =====================================
experiment:
  name: "stuart_landau_3000_experiment"
  version: "v1.0"
  description: "Stuart-Landau系3000時点×6次元データを用いたDFIV Kalman Filter本格実験"

  output:
    save_models: true
    save_predictions: true
    save_logs: true
    save_plots: true
    compress_results: false

  reproducibility:
    set_deterministic: true
    log_git_info: true
    save_environment: true

# =====================================
# ロギング設定
# =====================================
logging:
  level: "INFO"
  format: "detailed"
  save_to_file: true
  console_output: true

  progress:
    show_progress_bar: true
    update_frequency: 10

# =====================================
# 本格実験設定
# =====================================
debug:
  test_mode: false        # 本格実験モード
  quick_run: false
  verbose_training: true  # 詳細学習ログ
  save_intermediate: true # 中間結果保存
  memory_profiling: false

# =====================================
# Stuart-Landau系特有設定
# =====================================
dynamics:
  system_type: "stuart_landau"
  time_step: 0.01         # dt=0.01に対応
  oscillatory: true       # 振動系
  nonlinear: true         # 非線形
  dimension: 6            # 6次元系

  analysis:
    phase_space: true     # 位相空間解析
    limit_cycle: true     # リミットサイクル解析
    bifurcation: false    # 分岐解析（今回は単一パラメータ）