training:
  data_path:      "data/sim_complex_nonz.npz"  # simple or complex
  lr:             0.01
  seed:           42
  sv_weight_mode: "fixed"   # "fixed" or "L1" or "L2"
  # sv_weight (only used if sv_weight_mode: "fixed")
  sv_weight: !!float 1e-3

ssm:
  realization:
    past_horizon: 80
    jitter: !!float 1e-1
    cond_thresh: !!float 1e12
    rank: 3
    reg_type: 'abs'
  observation:
    past_horizon: 80  #=realization past_horizon
    kernel: "rbf"
    gamma: 0.01
    reg_lambda: !!float 1e-3

model:
  encoder_hidden: !!seq [!!int 6, !!int 6]
  decoder_hidden: !!seq [!!int 6, !!int 6]
  feature_dim: 6
  activation: "LeakyReLU"

visualization:
  output_dir: "results/figs"
